language: php

matrix:
  include:
    - php: 7.3.0
      env: LARAVEL=58
    - php: 7.3.0
      env: LARAVEL=57
    - php: 7.3.0
      env: LARAVEL=56
    - php: 7.3.0
      env: LARAVEL=55
    - php: 7.3.0
      env: LARAVEL=54
    - php: 7.3.0
      env: LARAVEL=53

    - php: 7.2.0
      env: LARAVEL=58
    - php: 7.2.0
      env: LARAVEL=57
    - php: 7.2.0
      env: LARAVEL=56
    - php: 7.2.0
      env: LARAVEL=55
    - php: 7.2.0
      env: LARAVEL=54
    - php: 7.2.0
      env: LARAVEL=53

    - php: 7.1.3
      env: LARAVEL=58
    - php: 7.1.3
      env: LARAVEL=57
    - php: 7.1.3
      env: LARAVEL=56
    - php: 7.1.3
      env: LARAVEL=55
    - php: 7.1.3
      env: LARAVEL=54
    - php: 7.1.3
      env: LARAVEL=53

    - php: 7.0.0
      env: LARAVEL=55
    - php: 7.0.0
      env: LARAVEL=54
    - php: 7.0.0
      env: LARAVEL=53

    - php: 5.6.4
      env: LARAVEL=54
    - php: 5.6.4
      env: LARAVEL=53

before_script:
  - travis_retry composer self-update
  - chmod +x tests/*.sh

script:
  - ./tests/laravel-${LARAVEL}.sh
  - cp phpunit.xml.dist phpunit.xml
  - php vendor/bin/phpunit