language: php

matrix:
  include:
    - php: 5.6.4
      env: PU_FILE=53
    - php: 5.6.4
      env: PU_FILE=54
    - php: 7.0.0
      env: PU_FILE=53
    - php: 7.0.0
      env: PU_FILE=54
    - php: 7.0.0
      env: PU_FILE=55
    - php: 7.1.3
      env: PU_FILE=53
    - php: 7.1.3
      env: PU_FILE=54
    - php: 7.1.3
      env: PU_FILE=55
    - php: 7.1.3
      env: PU_FILE=56
    - php: 7.1.3
      env: PU_FILE=57
    - php: 7.1.3
      env: PU_FILE=58
    - php: 7.2.0
      env: PU_FILE=53
    - php: 7.2.0
      env: PU_FILE=54
    - php: 7.2.0
      env: PU_FILE=55
    - php: 7.2.0
      env: PU_FILE=56
    - php: 7.2.0
      env: PU_FILE=57
    - php: 7.2.0
      env: PU_FILE=58
    - php: 7.3.0
      env: PU_FILE=53
    - php: 7.3.0
      env: PU_FILE=54
    - php: 7.3.0
      env: PU_FILE=55
    - php: 7.3.0
      env: PU_FILE=56
    - php: 7.3.0
      env: PU_FILE=57
    - php: 7.3.0
      env: PU_FILE=58

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - cp phpunit.xml.dist phpunit.xml
  - chmod +x tests/*.sh

script:
  - ./tests/pu-${PU_FILE}.sh
  - php vendor/bin/phpunit